export function createAIDriver({ nodes, blocked, getTraffic = () => [] }) {
  const state = {
    enabled: false, route: [], node: 0, goal: null, state: 'IDLE', mode: 'IDLE', tactical: 'CRUISE',
    sensor: { front: 999, frontLeft: 999, frontRight: 999, left: 999, right: 999 },
    dynamic: { count: 0, nearest: null, hazards: [] }, prediction: { safe: true, x: 0, y: 0, t: 0, ttc: Infinity, risk: 0 },
    horizons: [], candidates: [], chosenCandidate: 0, predictedTrajectory: [],
    crossTrack: 0, curvature: 0, headingError: 0, laneOffset: 0, targetSpeed: 0,
    replans: 0, recoveries: 0, safeStarts: 0, stuckTime: 0, contactTime: 0, progressTimer: 0, routeTimer: 0,
    lastProgressX: 0, lastProgressY: 0, distance: 0, visited: new Set(), lap: 0, decisions: 0,
    collisionsAvoided: 0, nearMisses: 0, overtakes: 0, debug: true,
    control: { throttle: 0, brake: 0, steer: 0, handbrake: false }
  };
  const clamp = (v,a,b)=>Math.max(a,Math.min(b,v));
  const dist = (a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
  const wrap = a=>{while(a>Math.PI)a-=Math.PI*2;while(a<-Math.PI)a+=Math.PI*2;return a;};
  const dot = (ax,ay,bx,by)=>ax*bx+ay*by;
  let seed=0x51f15e; const rand=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};

  function nearestNode(x,y){let best=nodes[0],bd=Infinity;for(const n of nodes){const d=(n.x-x)**2+(n.y-y)**2;if(d<bd){bd=d;best=n;}}return best;}
  function route(start,goal){if(!start||!goal)return[];const q=[start],cost=new Map([[start.id,0]]),prev=new Map([[start.id,null]]);for(let h=0;h<q.length;h++){const n=q[h];for(const m of n.links){const c=cost.get(n.id)+dist(n,m);if(!cost.has(m.id)||c<cost.get(m.id)){cost.set(m.id,c);prev.set(m.id,n);q.push(m);}}}if(!prev.has(goal.id))return[];const out=[];for(let n=goal;n;n=prev.get(n.id))out.push(n);return out.reverse();}
  function safePoint(n){if(!n||blocked(n.x,n.y)||n.links.length<2)return false;for(const a of[0,Math.PI/2,Math.PI,-Math.PI/2])if(!blocked(n.x+Math.cos(a)*42,n.y+Math.sin(a)*42))return true;return false;}
  function safeStart(car){const cs=nodes.filter(safePoint);if(!cs.length)return false;let n=cs[(rand()*cs.length)|0];for(let i=0;i<8;i++){const t=cs[(rand()*cs.length)|0];if(t.links.length>n.links.length)n=t;}const exits=n.links.filter(m=>!blocked((n.x+m.x)*.5,(n.y+m.y)*.5));const next=exits[(rand()*exits.length)|0]||n.links[0];car.x=n.x;car.y=n.y;car.a=Math.atan2(next.y-n.y,next.x-n.x);car.vx=car.vy=0;state.safeStarts++;state.lastProgressX=car.x;state.lastProgressY=car.y;return true;}
  function ray(car,angle,max,step=6){for(let d=10;d<=max;d+=step)if(blocked(car.x+Math.cos(angle)*d,car.y+Math.sin(angle)*d))return d;return max;}
  function sense(car){const a=car.a;state.sensor.front=ray(car,a,360);state.sensor.frontLeft=ray(car,a-.34,320);state.sensor.frontRight=ray(car,a+.34,320);state.sensor.left=ray(car,a-Math.PI/2,210);state.sensor.right=ray(car,a+Math.PI/2,210);return state.sensor;}
  function dynamicHazards(car){const fx=Math.cos(car.a),fy=Math.sin(car.a),hs=[];for(const o of getTraffic()||[]){if(!o||o===car)continue;const dx=o.x-car.x,dy=o.y-car.y,lon=dot(dx,dy,fx,fy),latSigned=dot(dx,dy,-fy,fx),lat=Math.abs(latSigned);if(lon<-90||lon>520||lat>105)continue;const ovx=Math.cos(o.a||0)*(o.v||0),ovy=Math.sin(o.a||0)*(o.v||0),rvx=car.vx-ovx,rvy=car.vy-ovy,closing=dot(rvx,rvy,fx,fy),gap=Math.max(0,lon-28),ttc=closing>5?gap/closing:Infinity;hs.push({o,longitudinal:lon,lateral:lat,lateralSigned:latSigned,ttc,closing,speed:o.v||0});}hs.sort((a,b)=>a.longitudinal-b.longitudinal);state.dynamic={count:hs.length,nearest:hs[0]||null,hazards:hs};return hs;}
  function segmentInfo(car){if(state.route.length<2)return{heading:car.a,cross:0,curvature:0,distance:Infinity,index:0,width:46};let best=null;const from=Math.max(0,state.node-3),to=Math.min(state.route.length-2,state.node+5);for(let i=from;i<=to;i++){const a=state.route[i],b=state.route[i+1],dx=b.x-a.x,dy=b.y-a.y,l2=dx*dx+dy*dy||1,t=clamp(((car.x-a.x)*dx+(car.y-a.y)*dy)/l2,0,1),px=a.x+dx*t,py=a.y+dy*t,d=Math.hypot(car.x-px,car.y-py);if(!best||d<best.distance)best={a,b,heading:Math.atan2(dy,dx),cross:((car.x-px)*(-dy)+(car.y-py)*dx)/Math.sqrt(l2),distance:d,index:i,t};}const i=best.index,p1=state.route[i],p2=state.route[Math.min(state.route.length-1,i+1)],p3=state.route[Math.min(state.route.length-1,i+2)],h1=Math.atan2(p2.y-p1.y,p2.x-p1.x),h2=Math.atan2(p3.y-p2.y,p3.x-p2.x);return{...best,curvature:Math.abs(wrap(h2-h1)),nextHeading:h2,width:46};}
  function lookahead(car,meters){if(!state.route.length)return nearestNode(car.x,car.y);let i=Math.min(state.node,state.route.length-1),p=state.route[i],remain=meters;while(i+1<state.route.length){const n=state.route[i+1],len=dist(p,n)||1;if(len>=remain)return{x:p.x+(n.x-p.x)*remain/len,y:p.y+(n.y-p.y)*remain/len};remain-=len;p=n;i++;}return p;}
  function simulate(car,seconds,steer,throttle,brake=0){const c={x:car.x,y:car.y,a:car.a,vx:car.vx,vy:car.vy},points=[],steps=Math.max(3,Math.ceil(seconds/.05)),h=seconds/steps;let minWall=999,collision=false,collisionT=seconds;for(let i=0;i<steps;i++){const fx=Math.cos(c.a),fy=Math.sin(c.a),rx=-fy,ry=fx,fs=dot(c.vx,c.vy,fx,fy),ls=dot(c.vx,c.vy,rx,ry);c.vx+=fx*throttle*450*h;c.vy+=fy*throttle*450*h;if(brake>0){const amount=Math.min(Math.abs(fs),780*brake*h);c.vx-=fx*Math.sign(fs||1)*amount;c.vy-=fy*Math.sign(fs||1)*amount;}c.vx-=rx*ls*Math.min(1,10.5*h);c.vy-=ry*ls*Math.min(1,10.5*h);c.vx*=Math.pow(.993,h*60);c.vy*=Math.pow(.993,h*60);const forward=dot(c.vx,c.vy,fx,fy),authority=clamp(Math.abs(forward)/55,0,1);c.a+=steer*1.9*authority*h*(forward>=0?1:-1);const nx=c.x+c.vx*h,ny=c.y+c.vy*h;minWall=Math.min(minWall,ray({x:c.x,y:c.y,a:c.a},c.a,80),ray({x:c.x,y:c.y,a:c.a},c.a+.3,65),ray({x:c.x,y:c.y,a:c.a},c.a-.3,65));if(blocked(nx,ny)){collision=true;collisionT=i*h;break;}c.x=nx;c.y=ny;if(i%2===0)points.push({x:c.x,y:c.y});}return{safe:!collision,collisionT,x:c.x,y:c.y,points,minWall,speed:Math.hypot(c.vx,c.vy)};}
  function trafficRisk(result,hs){let risk=0,minTtc=Infinity;for(const h of hs.slice(0,6)){minTtc=Math.min(minTtc,h.ttc);const o=h.o,ovx=Math.cos(o.a||0)*(o.v||0),ovy=Math.sin(o.a||0)*(o.v||0);for(const t of[.4,.8,1.2]){const qx=o.x+ovx*t,qy=o.y+ovy*t,d=Math.hypot(result.x-qx,result.y-qy),allow=34+result.speed*.06;if(d<allow)risk+=(allow-d)*(1.35-t*.3);}}return{risk,minTtc};}
  function candidateScore(car,c,seg,hs){const p=simulate(car,c.horizon,c.steer,c.throttle,c.brake),tr=trafficRisk(p,hs),target=lookahead(car,Math.max(120,c.horizon*155)),progress=-Math.hypot(p.x-target.x,p.y-target.y),lateral=Math.abs(seg.cross+c.laneOffset*32+Math.sin(c.steer)*c.horizon*Math.max(30,Math.hypot(car.vx,car.vy))),wall=Math.max(0,75-p.minWall)*4,collision=p.safe?0:100000+(c.horizon-p.collisionT)*7000,comfort=Math.abs(c.steer)*42+c.brake*35+Math.abs(c.laneOffset)*8,ttcPenalty=tr.minTtc<2.4?Math.max(0,2.4-tr.minTtc)*260:0;return{...c,...p,trafficRisk:tr.risk,ttc:tr.minTtc,score:progress-lateral*.85-wall-tr.risk*4-ttcPenalty-collision-comfort+(c.overtake?32:0)};}
  function chooseControl(car){const s=sense(car),hs=dynamicHazards(car),seg=segmentInfo(car),v=Math.hypot(car.vx,car.vy),look=lookahead(car,clamp(115+v*.5+seg.curvature*90,115,300)),desired=Math.atan2(look.y-car.y,look.x-car.x),headingError=wrap(desired-car.a);state.headingError=headingError;const center=clamp(seg.cross/55,-1.4,1.4),baseSteer=clamp(headingError*1.6-center*.82,-1,1);let desiredSpeed=435-seg.curvature*210-Math.min(75,Math.abs(seg.cross)*.7);if(Math.abs(headingError)>.8)desiredSpeed-=95;const lead=hs.find(h=>h.longitudinal>0&&h.longitudinal<250);let tactical='CRUISE',laneBias=0;if(lead&&lead.ttc<3.5&&s.front<210){const sideFree=s.left>95||s.right>95;if(sideFree&&seg.curvature<.55&&v>90){tactical='OVERTAKE';laneBias=s.left>s.right?-1:1;}else tactical='FOLLOW';if(lead.ttc<2.1)desiredSpeed=Math.min(desiredSpeed,Math.max(50,v-(2.1-lead.ttc)*145));}if(s.front<105)desiredSpeed=Math.min(desiredSpeed,Math.max(35,s.front*2));state.tactical=tactical;state.laneOffset=laneBias;const cs=[];for(const so of[-1,-.5,0,.5,1])for(const throttle of[0,.45,1]){const los=tactical==='OVERTAKE'?[laneBias,0,-laneBias]:[0];for(const lo of los){const brake=throttle===0?clamp((v-desiredSpeed)/130,0,1):0;cs.push(candidateScore(car,{steer:clamp(baseSteer+so*.38+lo*.12,-1,1),throttle,brake,horizon:v>260?.9:1.2,laneOffset:lo,overtake:tactical==='OVERTAKE'&&lo===laneBias},seg,hs));}}cs.sort((a,b)=>b.score-a.score);const best=cs[0];state.candidates=cs.slice(0,9).map((c,i)=>({rank:i+1,steer:+c.steer.toFixed(3),throttle:c.throttle,brake:+c.brake.toFixed(3),lane:c.laneOffset,overtake:!!c.overtake,safe:c.safe,score:Math.round(c.score),collisionT:+c.collisionT.toFixed(2),ttc:Number.isFinite(c.ttc)?+c.ttc.toFixed(2):Infinity}));state.chosenCandidate=0;state.targetSpeed=desiredSpeed;if(tactical==='OVERTAKE'&&best.overtake)state.overtakes++;let mode='CRUISE';if(!best.safe)mode='REPLAN';else if(best.brake>.2||s.front<85)mode='BRAKE';else if(tactical==='OVERTAKE')mode='OVERTAKE';else if(hs[0]?.ttc<1.5)mode='AVOID';else if(seg.curvature>.45)mode='CORNER';else if(Math.abs(seg.cross)>65)mode='LANE_CORRECT';state.mode=state.state=mode;state.decisions++;const preds=[.4,.8,1.2].map(t=>simulate(car,t,best.steer,best.throttle,best.brake)),last=preds[2],tr=trafficRisk(last,hs);state.predictedTrajectory=preds.flatMap(p=>p.points);state.prediction={safe:best.safe&&tr.risk<10,x:last.x,y:last.y,t:best.collisionT,ttc:tr.minTtc,risk:clamp((1-Math.min(1,best.minWall/100))+tr.risk/40+(best.safe?0:1),0,2)};state.horizons=preds.map((p,i)=>({t:[.4,.8,1.2][i],x:p.x,y:p.y,safe:p.safe,wall:p.minWall}));state.crossTrack=seg.cross||0;state.curvature=seg.curvature||0;state.control={throttle:best.throttle,brake:best.brake,steer:best.steer,handbrake:Math.abs(headingError)>1.9&&v>210};if(state.prediction.ttc<1.2)state.nearMisses++;return state.control;}
  function chooseGoal(car){const origin=nearestNode(car.x,car.y),pool=nodes.filter(n=>n.id!==origin?.id&&safePoint(n));if(!pool.length)return origin;let best=pool[0],score=-Infinity;for(const n of pool){const d=dist(origin,n),variety=Math.abs((n.x*13+n.y*7)%997),s=d+variety*.2;if(s>score){score=s;best=n;}}return best;}
  function ensureRoute(car,force=false){const origin=nearestNode(car.x,car.y);if(!force&&state.route.length&&state.node<state.route.length-1)return true;const goal=state.goal&&safePoint(state.goal)?state.goal:chooseGoal(car),r=route(origin,goal);if(!r.length)return false;state.goal=goal;state.route=r;state.node=0;state.routeTimer=0;state.replans++;return true;}
  function recover(car){const cs=nodes.filter(n=>safePoint(n));if(!cs.length)return false;let best=cs[0],bd=Infinity;for(const n of cs){const d=dist(car,n);if(d<bd){bd=d;best=n;}}const next=best.links[0];car.x=best.x;car.y=best.y;if(next)car.a=Math.atan2(next.y-best.y,next.x-best.x);car.vx=car.vy=0;state.recoveries++;state.mode=state.state='RECOVER';state.stuckTime=0;state.route=[];state.goal=null;return true;}
  function start(car){state.enabled=true;state.route=[];state.goal=null;state.node=0;state.distance=0;state.visited.clear();state.lap=0;safeStart(car);ensureRoute(car,true);}
  function update(car,dt){if(!state.enabled)start(car);state.routeTimer+=dt;const v=Math.hypot(car.vx,car.vy);state.distance+=v*dt;const moved=Math.hypot(car.x-state.lastProgressX,car.y-state.lastProgressY);if(moved>4){state.lastProgressX=car.x;state.lastProgressY=car.y;state.progressTimer=0;state.stuckTime=Math.max(0,state.stuckTime-dt);}else if(v<35)state.stuckTime+=dt;else state.progressTimer+=dt;if(!state.route.length||state.routeTimer>18||state.node>=state.route.length-1){if(!ensureRoute(car,true))return null;state.routeTimer=0;}while(state.node+1<state.route.length&&dist(car,state.route[state.node+1])<54){state.node++;state.visited.add(state.route[state.node].id);}const c=chooseControl(car);if(state.stuckTime>2.8){if(recover(car))ensureRoute(car,true);}if(state.prediction.ttc<.75)state.collisionsAvoided++;return c;}
  return { state, start, update, recover: car=>recover(car) };
}
