import { CITY_ROADS, CITY_DESTINATIONS, roadPoint } from './city_semantics.js';

const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function hash(x,y,n=0){const v=Math.sin(x*12.9898+y*78.233+n*37.719)*43758.5453;return v-Math.floor(v);}
function diamond(ctx,p,size){ctx.beginPath();ctx.moveTo(p.x,p.y-size*.45);ctx.lineTo(p.x+size,p.y);ctx.lineTo(p.x,p.y+size*.45);ctx.lineTo(p.x-size,p.y);ctx.closePath();}
function buildingDetails(ctx,iso,b,t){const [x,y,w,h]=b;const seed=hash(x,y,w+h);if(w>95&&h>95){const p=iso(x+w*.72,y+h*.24);ctx.save();ctx.translate(p.x,p.y-58);ctx.fillStyle='rgba(10,12,14,.82)';ctx.fillRect(-8,-5,16,10);ctx.strokeStyle='rgba(154,160,168,.42)';ctx.lineWidth=1;ctx.strokeRect(-8,-5,16,10);ctx.beginPath();ctx.moveTo(-4,-5);ctx.lineTo(-4,-14);ctx.moveTo(4,-5);ctx.lineTo(4,-14);ctx.stroke();ctx.restore();}if(seed>.55&&w>120){const levels=Math.max(1,Math.floor(h/105));ctx.strokeStyle='rgba(154,160,168,.25)';ctx.lineWidth=1;for(let i=1;i<=levels;i++){const yy=y+h-i*(h/(levels+1)),p1=iso(x+w*.08,yy),p2=iso(x+w*.42,yy);ctx.beginPath();ctx.moveTo(p1.x,p1.y-24);ctx.lineTo(p2.x,p2.y-24);ctx.stroke();}}if(seed>.82&&w>110){const p=iso(x+w*.56,y+h*.04);ctx.save();ctx.translate(p.x,p.y-34);ctx.fillStyle='rgba(12,13,16,.92)';ctx.fillRect(-20,-7,40,14);ctx.strokeStyle='rgba(224,154,62,.55)';ctx.strokeRect(-20,-7,40,14);ctx.fillStyle='rgba(224,154,62,.75)';ctx.font='bold 6px monospace';ctx.textAlign='center';ctx.fillText('LOW',0,2);ctx.restore();}if(w>80){ctx.strokeStyle='rgba(0,0,0,.20)';ctx.lineWidth=2;const p=iso(x+w*.14,y+h*.72),q=iso(x+w*.14,y+h*.91);ctx.beginPath();ctx.moveTo(p.x,p.y-28);ctx.lineTo(q.x,q.y-28);ctx.stroke();}if(seed<.32){const r=clamp(w*.055,4,11),p=iso(x+w*.5,y+h+4);ctx.fillStyle='rgba(224,154,62,.08)';diamond(ctx,p,r);ctx.fill();}void t;}
function streetAtmosphere(ctx,iso,lamps,t){for(let i=0;i<lamps.length;i++){const [x,y]=lamps[i],p=iso(x,y),pulse=.92+.08*Math.sin(t*2.4+i*.73),r=clamp(18*pulse,12,22),g=ctx.createRadialGradient(p.x,p.y-39,1,p.x,p.y-39,r);g.addColorStop(0,'rgba(255,211,130,.20)');g.addColorStop(.32,'rgba(224,154,62,.09)');g.addColorStop(1,'rgba(224,154,62,0)');ctx.fillStyle=g;ctx.beginPath();ctx.arc(p.x,p.y-39,r,0,Math.PI*2);ctx.fill();}}
function wetStreetSheen(ctx,iso,buildings,t){for(let i=0;i<buildings.length;i++){const [x,y,w,h]=buildings[i];if(i%3!==0)continue;const p=iso(x+w*.5,y+h+12),len=clamp(w*.22,18,54),shimmer=.45+.25*Math.sin(t*1.7+i*1.91);ctx.strokeStyle=`rgba(224,154,62,${.045*shimmer})`;ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(p.x-len,p.y);ctx.lineTo(p.x+len,p.y);ctx.stroke();}}
function roadLabels(ctx,iso){ctx.save();ctx.textAlign='center';ctx.textBaseline='middle';for(const road of CITY_ROADS){const mid=Math.floor((road.points.length-1)/2),p=roadPoint(road.id,mid,road.lanes*18+18);if(!p)continue;const q=iso(p.x,p.y);ctx.translate(q.x,q.y-8);ctx.rotate(-p.heading*.55);ctx.font=road.class==='ARTERIAL'?'bold 8px monospace':'7px monospace';ctx.fillStyle='rgba(224,154,62,.68)';ctx.fillText(road.name.toUpperCase(),0,0);ctx.setTransform(1,0,0,1,0,0);}ctx.restore();}
function intersections(ctx,iso){for(const road of CITY_ROADS){for(let i=0;i<road.points.length;i++){const [x,y]=road.points[i],connections=CITY_ROADS.filter(r=>r.id!==road.id&&r.points.some(p=>Math.hypot(p[0]-x,p[1]-y)<3));if(connections.length===0)continue;const p=iso(x,y);ctx.strokeStyle='rgba(154,160,168,.22)';ctx.lineWidth=3;for(const s of [-1,1]){ctx.beginPath();ctx.moveTo(p.x-10*s,p.y-4);ctx.lineTo(p.x+10*s,p.y+4);ctx.stroke();}}}}
function destinationSigns(ctx,iso){for(const d of CITY_DESTINATIONS){const p=roadPoint(d.roadId,d.index,(CITY_ROADS.find(r=>r.id===d.roadId)?.lanes||2)*14+30);if(!p)continue;const q=iso(p.x,p.y);ctx.fillStyle='rgba(12,13,16,.8)';ctx.fillRect(q.x-30,q.y-28,60,11);ctx.fillStyle='rgba(154,160,168,.72)';ctx.font='6px monospace';ctx.textAlign='center';ctx.fillText(d.name.toUpperCase(),q.x,q.y-20);}}
export function createCityVisuals(){return{version:'CITY_LIFE_1',draw(ctx,iso,buildings,lamps,t){for(const b of buildings)buildingDetails(ctx,iso,b,t);wetStreetSheen(ctx,iso,buildings,t);streetAtmosphere(ctx,iso,lamps,t);intersections(ctx,iso);roadLabels(ctx,iso);destinationSigns(ctx,iso);}};}
