import { PED_ASSETS } from './assets.js';
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const wrapAngle=a=>{while(a>Math.PI)a-=Math.PI*2;while(a<-Math.PI)a+=Math.PI*2;return a;};
export function createPeopleSystem({nodes,blocked,seed=4242}){
 let state=seed>>>0;const people=[],rand=()=>{state=(state*1664525+1013904223)>>>0;return state/4294967296};
 const activeNodes=nodes||[],pick=()=>activeNodes.length?activeNodes[(rand()*activeNodes.length)|0]:{x:0,y:0,links:[]};
 const sprite=k=>{const i=new Image();i.src=PED_ASSETS[k];return i};const sprites={civilian:sprite('civilian'),runner:sprite('runner')};
 const sidewalkPoint=n=>{for(let attempt=0;attempt<12;attempt++){const next=n?.links?.[(rand()*Math.max(1,n.links?.length||1))|0]||n;if(!next)continue;const dx=next.x-n.x,dy=next.y-n.y,len=Math.hypot(dx,dy)||1,side=rand()<.5?-1:1,offset=52+rand()*12,p={x:n.x-dy/len*offset*side,y:n.y+dx/len*offset*side};if(!blocked(p.x,p.y))return p;}return{x:n.x,y:n.y};};
 const freeSidewalkPoint=(cars=[],origin=null)=>{for(let i=0;i<activeNodes.length*2;i++){const p=sidewalkPoint(pick());if(origin&&Math.hypot(p.x-origin.x,p.y-origin.y)<24)continue;if(people.some(q=>Math.hypot(q.x-p.x,q.y-p.y)<30))continue;if(cars.some(q=>Math.hypot(q.x-p.x,q.y-p.y)<48))continue;return p;}return sidewalkPoint(pick());};
 const chooseTarget=(p,cars=[])=>{const target=freeSidewalkPoint(cars,p);p.target=target;p.timer=2+rand()*5;p.state=rand()<.12?'idle':'walk';p.waypoint=0;};
 for(let i=0;i<Math.min(28,activeNodes.length);i++){const q=freeSidewalkPoint();people.push({x:q.x,y:q.y,a:0,v:18+rand()*10,state:'walk',timer:rand()*3,tone:rand(),target:freeSidewalkPoint(),route:[],waypoint:0,panic:0,stuck:0});}
 function update(dt,player,danger=0,cars=[]){const h=Math.min(Math.max(Number(dt)||0,0),.05);for(const p of people){p.timer-=h;const pd=player?Math.hypot(player.x-p.x,player.y-p.y):Infinity;if(danger>0&&pd<240)p.panic=Math.min(1,p.panic+h*2);else p.panic=Math.max(0,p.panic-h*.8);if(p.timer<=0||Math.hypot(p.target.x-p.x,p.target.y-p.y)<18)chooseTarget(p,cars);if(p.state==='idle'&&p.panic<.2)continue;let desired=Math.atan2(p.target.y-p.y,p.target.x-p.x);if(p.panic>.2&&pd<240)desired=Math.atan2(p.y-player.y,p.x-player.x);const d=wrapAngle(desired-p.a),turn=1-Math.exp(-10*h);p.a=wrapAngle(p.a+d*turn);const targetSpeed=p.v*(p.panic>.2?1.6:1),nx=p.x+Math.cos(p.a)*targetSpeed*h,ny=p.y+Math.sin(p.a)*targetSpeed*h;const nearCar=cars.some(c=>Math.hypot(c.x-nx,c.y-ny)<42);const nearPed=people.some(q=>q!==p&&Math.hypot(q.x-nx,q.y-ny)<22);if(!blocked(nx,ny)&&!nearCar&&!nearPed){p.x=nx;p.y=ny;p.stuck=0;}else{p.stuck+=h;p.a=wrapAngle(p.a+(rand()<.5?-1:1)*1.1*h);if(p.stuck>.45){chooseTarget(p,cars);p.stuck=0;}}}}
 function draw(ctx,iso,player){const ordered=[...people].sort((a,b)=>(a.x+a.y)-(b.x+b.y));for(const p of ordered){const q=iso(p.x,p.y),f=iso(p.x+Math.cos(p.a)*8,p.y+Math.sin(p.a)*8),ang=Math.atan2(f.y-q.y,f.x-q.x),image=sprites[p.panic>.2?'runner':'civilian'];ctx.save();ctx.translate(q.x,q.y);ctx.rotate(ang);if(image.complete&&image.naturalWidth)ctx.drawImage(image,-12,-16,24,18);else{ctx.fillStyle='#596068';ctx.beginPath();ctx.arc(0,-8,4,0,Math.PI*2);ctx.fill();ctx.fillRect(-3,-4,6,11);}ctx.restore();}}
 return{people,update,draw};
}
