import { VEHICLE_ASSETS } from './assets.js';

export function createTrafficSystem({ nodes, blocked, seed = 1337 }) {
  let state = seed >>> 0; const cars=[]; const images={};
  Object.entries(VEHICLE_ASSETS).forEach(([k,src])=>{const i=new Image();i.src=src;images[k]=i});
  const rand=()=>{state=(state*1664525+1013904223)>>>0;return state/4294967296};
  const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),pickNode=()=>nodes[(rand()*nodes.length)|0];
  const routeFrom=start=>{const route=[start];let cur=start;const seen=new Set([cur.id]);for(let i=0;i<18;i++){const choices=cur.links.filter(n=>!seen.has(n.id));if(!choices.length)break;cur=choices[(rand()*choices.length)|0];route.push(cur);seen.add(cur.id)}return route};
  const lanePoint=(node,next,lane)=>{if(!next)return{x:node.x,y:node.y};const dx=next.x-node.x,dy=next.y-node.y,len=Math.hypot(dx,dy)||1;return{x:node.x-dy/len*lane,y:node.y+dx/len*lane}};
  const occupied=n=>cars.some(c=>dist(c,n)<110);
  const types=['sedan','coupe','taxi','police','van','truck'];
  for(let i=0;i<22;i++){let n=pickNode(),tries=0;while(occupied(n)&&tries++<30)n=pickNode();const next=n.links[0],type=types[(rand()*types.length)|0];cars.push({x:n.x,y:n.y,a:next?Math.atan2(next.y-n.y,next.x-n.x):rand()*Math.PI*2,v:75+rand()*65,targetSpeed:105+rand()*95,route:routeFrom(n),index:1,lane:(rand()<.5?-1:1)*22,type,tone:rand(),stuck:0,brake:0,lights:type==='police'||type==='taxi'})}
  function update(dt,player){for(const car of cars){let node=car.route[car.index],next=car.route[car.index+1];if(!node||dist(car,node)<22){if(node)car.index++;if(!car.route[car.index]){const start=car.route.at(-1)||pickNode();car.route=routeFrom(start);car.index=1}node=car.route[car.index];next=car.route[car.index+1]}if(!node)continue;const aim=lanePoint(node,next||node,car.lane),desired=Math.atan2(aim.y-car.y,aim.x-car.x);let d=desired-car.a;while(d>Math.PI)d-=Math.PI*2;while(d<-Math.PI)d+=Math.PI*2;const steer=Math.max(-1,Math.min(1,d*2.7));car.a+=steer*1.9*dt*Math.min(1,car.v/45);let desiredSpeed=car.targetSpeed*(1-Math.min(.7,Math.abs(d)*.5));if(Math.abs(d)>.9)desiredSpeed*=.62;let lead=Infinity;for(const other of cars){if(other===car)continue;const dx=other.x-car.x,dy=other.y-car.y,ahead=dx*Math.cos(car.a)+dy*Math.sin(car.a),side=Math.abs(-dx*Math.sin(car.a)+dy*Math.cos(car.a));if(ahead>0&&ahead<105&&side<30)lead=Math.min(lead,ahead)}if(player){const dx=player.x-car.x,dy=player.y-car.y,ahead=dx*Math.cos(car.a)+dy*Math.sin(car.a),side=Math.abs(-dx*Math.sin(car.a)+dy*Math.cos(car.a));if(ahead>0&&ahead<90&&side<34)lead=Math.min(lead,ahead)}if(lead<80)desiredSpeed=Math.min(desiredSpeed,Math.max(0,(lead-18)*2.4));car.brake=Math.max(0,Math.min(1,car.brake+(desiredSpeed<car.v?1:-2)*dt));car.v+=(desiredSpeed-car.v)*Math.min(1,dt*(desiredSpeed<car.v?4.5:1.7));const nx=car.x+Math.cos(car.a)*car.v*dt,ny=car.y+Math.sin(car.a)*car.v*dt;if(!blocked(nx,ny)){car.x=nx;car.y=ny;car.stuck=0}else{car.v*=.35;car.a+=(rand()-.5)*.8;car.stuck+=dt}if(car.stuck>1.5){const n=pickNode();car.x=n.x;car.y=n.y;car.route=routeFrom(n);car.index=1;car.stuck=0}}}
  function draw(ctx,iso){for(const car of cars){const p=iso(car.x,car.y),image=images[car.type];ctx.save();ctx.translate(p.x,p.y);ctx.rotate(-car.a-.15);if(image?.complete)ctx.drawImage(image,-24,-12,48,24);else{ctx.fillStyle='#3d4146';ctx.fillRect(-20,-9,40,18)}if(car.type==='police'){ctx.fillStyle=Math.sin(performance.now()/90)>0?'#d4523a':'#9aa0a8';ctx.fillRect(-4,-13,8,3)}ctx.restore()}}
  return {cars,update,draw};
}
