import { VEHICLE_ASSETS } from './assets.js';
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const angleDelta=(target,current)=>{let d=target-current;while(d>Math.PI)d-=Math.PI*2;while(d<-Math.PI)d+=Math.PI*2;return d;};
export function createTrafficSystem({nodes,blocked,seed=1337}){
 let state=seed>>>0;const cars=[],images={};Object.entries(VEHICLE_ASSETS).forEach(([k,src])=>{const i=new Image();i.src=src;images[k]=i});
 const params=new URLSearchParams(location.search);let scenario=null;try{const raw=params.get('scenario');if(raw)scenario=JSON.parse(raw)}catch{}
 const density=Number.isFinite(Number(scenario?.trafficDensity))?clamp(Number(scenario.trafficDensity),0,1):null;
 const leadSpeed=Number.isFinite(Number(scenario?.leadSpeed))?Math.max(25,Number(scenario.leadSpeed)):null;
 const activeNodes=(globalThis.__LOWTOWN_CITY_GRAPH?.length?globalThis.__LOWTOWN_CITY_GRAPH:nodes);
 const rand=()=>{state=(state*1664525+1013904223)>>>0;return state/4294967296};
 const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),pick=()=>activeNodes[(rand()*activeNodes.length)|0];
 function chooseNext(current,previous){const choices=(current?.links||[]).filter(n=>!previous||n.id!==previous.id);if(!choices.length)return current?.links?.[0]||null;if(!previous)return choices[0];const incoming=Math.atan2(current.y-previous.y,current.x-previous.x);let best=choices[0],score=-Infinity;for(const n of choices){const out=Math.atan2(n.y-current.y,n.x-current.x),turn=Math.abs(angleDelta(out,incoming));const straight=1-turn/Math.PI;const roadBonus=n.roadId===current.roadId?.35:0;const scoreNow=straight*2+roadBonus+rand()*.08;if(scoreNow>score){score=scoreNow;best=n;}}return best;}
 const buildRoute=start=>{const route=[start];let prev=null,current=start;for(let i=0;i<28;i++){const next=chooseNext(current,prev);if(!next||route.some(n=>n.id===next.id))break;route.push(next);prev=current;current=next;}return route;};
 const lane=(n,next,l)=>{if(!next)return{x:n.x,y:n.y};const dx=next.x-n.x,dy=next.y-n.y,len=Math.hypot(dx,dy)||1;return{x:n.x-dy/len*l,y:n.y+dx/len*l};};
 const types=[['sedan',105,165],['coupe',125,195],['taxi',115,175],['police',135,210],['van',85,135],['truck',70,115]];
 const count=density===null?18:Math.max(6,Math.min(36,Math.round(6+density*30)));
 for(let i=0;i<count;i++){const n=activeNodes[(i*7+((rand()*activeNodes.length)|0))%activeNodes.length],t=types[(rand()*types.length)|0],nx=n.links[0],v=leadSpeed===null?t[1]+rand()*(t[2]-t[1]):Math.max(25,leadSpeed*(.9+rand()*.2));cars.push({x:n.x,y:n.y,a:nx?Math.atan2(nx.y-n.y,nx.x-n.x):0,v,targetSpeed:v,route:buildRoute(n),index:1,lane:(rand()<.5?-1:1)*18,type:t[0],stuck:0,brake:0,siren:0,roadId:n.roadId||null,hitAt:0});}
 function update(dt,player,event=null){for(const c of cars){let n=c.route[c.index],next=c.route[c.index+1];if(!n||dist(c,n)<22){const previous=c.route[Math.max(0,c.index-1)];if(n)c.index++;if(!c.route[c.index]){const start=c.route.at(-1)||pick();c.route=buildRoute(start);c.index=1;}n=c.route[c.index];next=c.route[c.index+1];if(n)c.a=Math.atan2(n.y-c.y,n.x-c.x);}if(!n)continue;c.roadId=n.roadId||c.roadId;const target=lane(n,next,c.lane),desired=Math.atan2(target.y-c.y,target.x-c.x),d=angleDelta(desired,c.a),speedFactor=clamp(c.v/70,.25,1),maxTurn=1.35*dt*speedFactor;c.a+=clamp(d,-maxTurn,maxTurn);let want=c.targetSpeed*(1-clamp(Math.abs(d)/1.8,0,.62));let lead=Infinity;for(const o of cars){if(o===c)continue;const dx=o.x-c.x,dy=o.y-c.y,front=dx*Math.cos(c.a)+dy*Math.sin(c.a),side=Math.abs(-dx*Math.sin(c.a)+dy*Math.cos(c.a));if(front>0&&front<115&&side<28)lead=Math.min(lead,front);}if(player){const dx=player.x-c.x,dy=player.y-c.y,front=dx*Math.cos(c.a)+dy*Math.sin(c.a),side=Math.abs(-dx*Math.sin(c.a)+dy*Math.cos(c.a));if(front>0&&front<100&&side<30)lead=Math.min(lead,front);}if(lead<78)want=Math.min(want,Math.max(0,(lead-16)*2));c.v+=(want-c.v)*Math.min(1,dt*(want<c.v?6:2));const nx=c.x+Math.cos(c.a)*c.v*dt,ny=c.y+Math.sin(c.a)*c.v*dt;if(!blocked(nx,ny)){c.x=nx;c.y=ny;c.stuck=0;}else{c.v*=.5;c.stuck+=dt;}if(c.type==='police'&&player&&dist(c,player)<420){c.siren=1;const chase=angleDelta(Math.atan2(player.y-c.y,player.x-c.x),c.a);c.a+=clamp(chase,-.8*dt,.8*dt);}else c.siren=0;if(c.stuck>1.2){const s=pick(),to=s.links[0];c.x=s.x;c.y=s.y;c.a=to?Math.atan2(to.y-s.y,to.x-s.x):0;c.route=buildRoute(s);c.index=1;c.stuck=0;}}
 }
 function draw(ctx,iso){for(const c of cars){const center=iso(c.x,c.y),front=iso(c.x+Math.cos(c.a)*34,c.y+Math.sin(c.a)*34),back=iso(c.x-Math.cos(c.a)*26,c.y-Math.sin(c.a)*26),sideA=iso(c.x-Math.sin(c.a)*12,c.y+Math.cos(c.a)*12),sideB=iso(c.x+Math.sin(c.a)*12,c.y-Math.cos(c.a)*12);ctx.save();ctx.beginPath();ctx.moveTo(front.x,front.y);ctx.lineTo(sideB.x,sideB.y);ctx.lineTo(back.x,back.y);ctx.lineTo(sideA.x,sideA.y);ctx.closePath();ctx.fillStyle=c.type==='police'?'#30353a':c.type==='taxi'?'#e8b84a':c.type==='truck'?'#555b61':'#454a50';ctx.fill();ctx.strokeStyle='#101216';ctx.lineWidth=2;ctx.stroke();const windshield=iso(c.x+Math.cos(c.a)*10,c.y+Math.sin(c.a)*10);ctx.fillStyle='#15191d';ctx.beginPath();ctx.ellipse(windshield.x,windshield.y,7,4,Math.atan2(front.y-center.y,front.x-center.x),0,Math.PI*2);ctx.fill();if(c.type==='police'&&c.siren){ctx.fillStyle=Math.sin(performance.now()/90)>0?'#d4523a':'#e8b84a';ctx.fillRect(center.x-4,center.y-12,8,3);}ctx.restore();}}
 return{cars,update,draw,ai:null,scenario};
}
