import { VEHICLE_ASSETS } from './assets.js';
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const angleDelta=(target,current)=>{let d=target-current;while(d>Math.PI)d-=Math.PI*2;while(d<-Math.PI)d+=Math.PI*2;return d;};
export function createTrafficSystem({nodes,blocked,seed=1337}){
 let state=seed>>>0;const cars=[],images={};Object.entries(VEHICLE_ASSETS).forEach(([k,src])=>{const i=new Image();i.src=src;images[k]=i});
 const params=new URLSearchParams(location.search);let scenario=null;try{const raw=params.get('scenario');if(raw)scenario=JSON.parse(raw)}catch{}
 const density=Number.isFinite(Number(scenario?.trafficDensity))?clamp(Number(scenario.trafficDensity),0,1):null;
 const leadSpeed=Number.isFinite(Number(scenario?.leadSpeed))?Math.max(25,Number(scenario.leadSpeed)):null;
 const activeNodes=(globalThis.__LOWTOWN_CITY_GRAPH?.length?globalThis.__LOWTOWN_CITY_GRAPH:nodes);
 const rand=()=>{state=(state*1664525+1013904223)>>>0;return state/4294967296};
 const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),pickFree=(origin,minDist=150)=>{let best=null,bd=Infinity;for(const n of activeNodes){if(origin&&dist(n,origin)<minDist)continue;if(blocked(n.x,n.y))continue;const occupied=cars.some(c=>dist(c,n)<42);if(occupied)continue;const d=origin?dist(n,origin):0;if(!best||d<bd){best=n;bd=d;}}return best||activeNodes.find(n=>!blocked(n.x,n.y)&&!cars.some(c=>dist(c,n)<42))||null;};
 function chooseNext(current,previous){const choices=(current?.links||[]).filter(n=>!previous||n.id!==previous.id);if(!choices.length)return current?.links?.[0]||null;if(!previous)return choices[0];const incoming=Math.atan2(current.y-previous.y,current.x-previous.x);let best=choices[0],score=-Infinity;for(const n of choices){const out=Math.atan2(n.y-current.y,n.x-current.x),turn=Math.abs(angleDelta(out,incoming));const straight=1-turn/Math.PI;const roadBonus=n.roadId===current.roadId?.35:0;const scoreNow=straight*2+roadBonus+rand()*.08;if(scoreNow>score){score=scoreNow;best=n;}}return best;}
 const buildRoute=start=>{const route=[start];let prev=null,current=start;for(let i=0;i<28;i++){const next=chooseNext(current,prev);if(!next||route.some(n=>n.id===next.id))break;route.push(next);prev=current;current=next;}return route;};
 const lane=(n,next,l)=>{if(!next)return{x:n.x,y:n.y};const dx=next.x-n.x,dy=next.y-n.y,len=Math.hypot(dx,dy)||1;return{x:n.x-dy/len*l,y:n.y+dx/len*l};};
 const types=[['sedan',105,165],['coupe',125,195],['taxi',115,175],['police',135,210],['van',85,135],['truck',70,115]];
 const count=density===null?12:Math.max(6,Math.min(36,Math.round(6+density*30)));
 for(let i=0;i<count;i++){const n=pickFree(null,0)||activeNodes[(i*7+((rand()*activeNodes.length)|0))%activeNodes.length],t=types[(rand()*types.length)|0],nx=n?.links?.[0],v=leadSpeed===null?t[1]+rand()*(t[2]-t[1]):Math.max(25,leadSpeed*(.9+rand()*.2));cars.push({x:n.x,y:n.y,a:nx?Math.atan2(nx.y-n.y,nx.x-n.x):0,v,targetSpeed:v,route:buildRoute(n),index:1,lane:(rand()<.5?-1:1)*18,type:t[0],stuck:0,brake:0,siren:0,roadId:n.roadId||null,hitAt:0,hold:0,recovery:0});}
 globalThis.__LOWTOWN_TRAFFIC_CARS=cars;
 let collisions=[];
 function update(dt,player,event=null){
  collisions=[];const now=performance.now();
  const claims=new Map();for(const c of cars){const n=c.route[c.index];if(n)claims.set(n.id,(claims.get(n.id)||0)+1);}
  for(const c of cars){let n=c.route[c.index],next=c.route[c.index+1];if(!n||dist(c,n)<22){const previous=c.route[Math.max(0,c.index-1)];if(n)c.index++;if(!c.route[c.index]){const start=pickFree(c,90)||c.route.at(-1);c.route=buildRoute(start);c.index=1;}n=c.route[c.index];next=c.route[c.index+1];if(n)c.a=Math.atan2(n.y-c.y,n.x-c.x);}if(!n)continue;c.roadId=n.roadId||c.roadId;
   const target=lane(n,next,c.lane),desired=Math.atan2(target.y-c.y,target.x-c.x),d=angleDelta(desired,c.a),speedFactor=clamp(c.v/70,.25,1),maxTurn=1.35*dt*speedFactor;c.a+=clamp(d,-maxTurn,maxTurn);let want=c.targetSpeed*(1-clamp(Math.abs(d)/1.8,0,.62));let lead=Infinity;
   for(const o of cars){if(o===c)continue;const dx=o.x-c.x,dy=o.y-c.y,front=dx*Math.cos(c.a)+dy*Math.sin(c.a),side=Math.abs(-dx*Math.sin(c.a)+dy*Math.cos(c.a));if(front>0&&front<145&&side<48)lead=Math.min(lead,front);}if(player){const dx=player.x-c.x,dy=player.y-c.y,front=dx*Math.cos(c.a)+dy*Math.sin(c.a),side=Math.abs(-dx*Math.sin(c.a)+dy*Math.cos(c.a));if(front>0&&front<125&&side<48)lead=Math.min(lead,front);}if(lead<82)want=Math.min(want,Math.max(0,(lead-18)*1.8));
   const claimed=claims.get(n.id)||0;if(claimed>1&&dist(c,n)<105){c.hold=Math.min(1,c.hold+dt*3);want=Math.min(want,22);}else c.hold=Math.max(0,c.hold-dt*2);if(c.hold>0)want=Math.min(want,Math.max(0,22*(1-c.hold*.65)));
   c.v+=(want-c.v)*Math.min(1,dt*(want<c.v?8:2));const nx=c.x+Math.cos(c.a)*c.v*dt,ny=c.y+Math.sin(c.a)*c.v*dt;if(!blocked(nx,ny)){c.x=nx;c.y=ny;c.stuck=Math.max(0,c.stuck-dt*.5);}else{c.v*=.2;c.stuck+=dt;}
   if(c.type==='police'&&player&&dist(c,player)<420){c.siren=1;const chase=angleDelta(Math.atan2(player.y-c.y,player.x-c.x),c.a);c.a+=clamp(chase,-.8*dt,.8*dt);}else c.siren=0;
   if(c.stuck>1.2){c.v=0;c.brake=1;c.hold=.8;c.recovery++;c.stuck=0;const previous=c.route[Math.max(0,c.index-1)],current=c.route[c.index]||c.route.at(-1),reverse=current&&previous&&dist(current,previous)>1?previous:null;if(reverse&&!blocked(reverse.x,reverse.y)){c.route=buildRoute(reverse);c.index=1;c.a=Math.atan2(reverse.y-c.y,reverse.x-c.x);}else{const free=pickFree(c,110);if(free){c.route=buildRoute(free);c.index=1;c.a=Math.atan2(free.y-c.y,free.x-c.x);}}}
  }
  for(let i=0;i<cars.length;i++)for(let j=i+1;j<cars.length;j++){const a=cars[i],b=cars[j],dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy),minDist=40;if(d<minDist){const nx=dx/(d||1),ny=dy/(d||1),penetration=minDist-d,push=Math.min(18,Math.max(2,penetration*.85+1.2)),avx=a.v*Math.cos(a.a),avy=a.v*Math.sin(a.a),bvx=b.v*Math.cos(b.a),bvy=b.v*Math.sin(b.a),relative=(bvx-avx)*nx+(bvy-avy)*ny;a.x-=nx*push*.5;a.y-=ny*push*.5;b.x+=nx*push*.5;b.y+=ny*push*.5;if(relative<0){const damp=Math.min(.7,-relative*.24);a.v=Math.max(0,a.v-damp);b.v=Math.max(0,b.v-damp);}a.brake=Math.min(1,a.brake+.25);b.brake=Math.min(1,b.brake+.25);if(now-(a.hitAt||0)>500||now-(b.hitAt||0)>500){collisions.push({type:'npc-npc',a,b,relative});a.hitAt=now;b.hitAt=now;}}}
  if(player){for(const c of cars){const dx=c.x-player.x,dy=c.y-player.y,d=Math.hypot(dx,dy);if(d>0&&d<38){const nx=dx/d,ny=dy/d,corr=38-d;const rel=(c.v*Math.cos(c.a)-Number(player.vx||0))*nx+(c.v*Math.sin(c.a)-Number(player.vy||0))*ny;c.x+=nx*corr;c.y+=ny*corr;c.v=Math.min(c.v,24);c.brake=1;player.vx=(Number(player.vx)||0)-nx*Math.max(4,Math.min(18,-rel*.55));player.vy=(Number(player.vy)||0)-ny*Math.max(4,Math.min(18,-rel*.55));if(now-(c.hitAt||0)>500){collisions.push({type:'player-npc',car:c,relative:rel});c.hitAt=now;}}}}
 }
 function consumeCollisions(){const out=collisions;collisions=[];return out;}
 function draw(ctx,iso){const ordered=[...cars].sort((a,b)=>(a.x+a.y)-(b.x+b.y));for(const c of ordered){const center=iso(c.x,c.y),front=iso(c.x+Math.cos(c.a)*20,c.y+Math.sin(c.a)*20),screenAngle=Math.atan2(front.y-center.y,front.x-center.x);const image=images[c.type]||images.sedan;ctx.save();ctx.translate(center.x,center.y);ctx.rotate(screenAngle);ctx.globalAlpha=.98;if(c.type==='taxi')ctx.filter='grayscale(.72) brightness(.82)';if(image?.complete&&image.naturalWidth)ctx.drawImage(image,-30,-15,60,30);else{ctx.fillStyle='#454a50';ctx.fillRect(-22,-10,44,20);}ctx.restore();if(c.type==='police'&&c.siren){ctx.fillStyle=Math.sin(performance.now()/90)>0?'#d4523a':'#e8b84a';ctx.fillRect(center.x-4,center.y-18,8,3);}}}
 return{cars,update,draw,consumeCollisions,ai:null,scenario};
}
