import { createTransportState, transportStep, transportTelemetry } from './transport_physics.js';
import { TRANSPORT_TYPES } from './transport_constants.js';
import { getTransportProfile, getTransportTypeProfile, resolveTransportPhysics } from './transport_profiles.js';
import { applyActuatorDelay } from './vehicle_safety.js';
import { stepArcadeCar, resetArcadeCarState } from './arcade_car_physics.js';
import { isLand } from './islands.js';
import { WORLD } from './world.js';
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));const finite=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f;
function worldBlocked(x,y){if(!isLand(x,y))return true;const r=18;return WORLD.buildings.some(([bx,by,bw,bh])=>x>bx-r&&x<bx+bw+r&&y>by-r&&y<by+bh+r);}
function calibratedPhysics(base,calibration=null){if(!calibration||calibration.ready===false)return base;const confidence=clamp(finite(calibration.confidence,0),0,1),scale=(v,f=1)=>clamp(finite(v,f),.75,1.25),a=scale(calibration.accelerationScale),b=scale(calibration.brakingScale),s=scale(calibration.steeringScale),d=scale(calibration.dragScale),r=scale(calibration.turnRadiusScale);return{...base,engineForce:base.engineForce*(1+(a-1)*confidence),brakeForce:base.brakeForce*(1+(b-1)*confidence),steeringRate:base.steeringRate*(1+(s-1)*confidence),drag:base.drag*(1+(d-1)*confidence),turnRadius:base.turnRadius*(1+(r-1)*confidence),calibration:{accelerationScale:a,brakingScale:b,steeringScale:s,dragScale:d,turnRadiusScale:r,confidence}};}
function calibrationForVehicle(profile,id){return profile&&typeof profile==='object'?profile.vehicles?.[id]||null:null;}
function arcadeProfile(p,physics){return{maxForwardSpeed:Math.min(p.maxSpeed||physics.maxForwardSpeed||455,physics.maxForwardSpeed||455),arcadeAcceleration:p.arcadeAcceleration||145,arcadeReverseAcceleration:p.arcadeReverseAcceleration||85,arcadeBrake:p.arcadeBrake||420,arcadeDrag:p.arcadeDrag||2.8,wheelbase:p.wheelbase||58,maxSteering:p.maxSteering||.58,steeringRateArcade:p.steeringRateArcade||3.8};}
export function createTransportController(vehicleId='sedan',initial={}){
 let currentId=getTransportProfile(vehicleId).id;const profile=()=>getTransportProfile(currentId);const state=createTransportState({type:profile().type,vehicleId:currentId,mass:profile().mass,...initial});let calibrationProfile=null,calibrationByVehicle={};let physics=resolveTransportPhysics(currentId);state.mass=physics.mass;state.physics=physics;resetArcadeCarState(state);
 let lastInput={throttle:0,brake:0,steer:0,handbrake:false,climb:0,descend:0},actuator={throttle:0,brake:0,steer:0,climb:0,descend:0},actuatorResponse={steer:12,throttle:8,brake:16,climb:8,descend:8};
 function activeCalibration(){return calibrationByVehicle[currentId]||calibrationForVehicle(calibrationProfile,currentId);}function rebuildPhysics(){physics=calibratedPhysics(resolveTransportPhysics(currentId),activeCalibration());state.mass=physics.mass;state.physics=physics;return physics;}
 function setVehicle(id){const next=getTransportProfile(id);currentId=next.id;state.vehicleId=currentId;state.type=next.type;state.surface=next.type===TRANSPORT_TYPES.CAR?'road':next.type===TRANSPORT_TYPES.BOAT?'water':'air';resetActuators();resetArcadeCarState(state);rebuildPhysics();return next;}
 function setCalibration(next=null,vehicleId=currentId){const id=getTransportProfile(vehicleId).id;if(next&&typeof next==='object'){if(next.vehicles&&typeof next.vehicles==='object'){calibrationProfile={...next,vehicles:{...next.vehicles}};calibrationByVehicle={...calibrationByVehicle,...next.vehicles};}else calibrationByVehicle={...calibrationByVehicle,[id]:{...next}};}else if(next===null){delete calibrationByVehicle[id];if(calibrationProfile?.vehicles?.[id]){const vehicles={...calibrationProfile.vehicles};delete vehicles[id];calibrationProfile={...calibrationProfile,vehicles};}}rebuildPhysics();return activeCalibration();}
 function setCalibrationProfile(p={}){calibrationProfile=p&&typeof p==='object'?{...p,vehicles:{...(p.vehicles||{})}}:null;calibrationByVehicle={...(calibrationProfile?.vehicles||{})};rebuildPhysics();return calibrationProfile;}function getCalibration(vehicleId=currentId){return calibrationByVehicle[vehicleId]||calibrationProfile?.vehicles?.[vehicleId]||null;}
 function clearCalibration(vehicleId=currentId){const id=getTransportProfile(vehicleId).id;delete calibrationByVehicle[id];if(calibrationProfile?.vehicles?.[id]){const vehicles={...calibrationProfile.vehicles};delete vehicles[id];calibrationProfile={...calibrationProfile,vehicles};}rebuildPhysics();return physics;}function clearAllCalibration(){calibrationProfile=null;calibrationByVehicle={};rebuildPhysics();return physics;}
 function setActuatorResponse(next={}){actuatorResponse={...actuatorResponse,...Object.fromEntries(Object.entries(next).filter(([,v])=>Number.isFinite(Number(v))&&Number(v)>=0))};return {...actuatorResponse};}function resetActuators(){actuator={throttle:0,brake:0,steer:0,climb:0,descend:0};return {...actuator};}
 function control(input={},dt=1/60){const type=state.type,target={throttle:clamp(Number(input.throttle)||0,-1,1),brake:clamp(Number(input.brake)||0,0,1),steer:clamp(Number(input.steer)||0,-1,1),handbrake:type===TRANSPORT_TYPES.CAR&&!!input.handbrake,climb:type===TRANSPORT_TYPES.PLANE?clamp(Number(input.climb)||0,-1,1):0,descend:type===TRANSPORT_TYPES.PLANE?clamp(Number(input.descend)||0,0,1):0};if(type===TRANSPORT_TYPES.CAR&&target.throttle<0)target.brake=0;if(type===TRANSPORT_TYPES.PLANE)target.throttle=Math.max(0,target.throttle);const next=applyActuatorDelay(target,actuator,clamp(finite(dt),0,.1),actuatorResponse);actuator={throttle:next.throttle,brake:next.brake,steer:next.steer,climb:next.climb,descend:next.descend};lastInput={...next,handbrake:target.handbrake};return lastInput;}
 function step(dt,input=lastInput){const safeDt=clamp(finite(dt),0,.1);control(input,safeDt);const old={x:state.x,y:state.y,z:state.z,a:state.a,v:state.v,vx:state.vx,vy:state.vy,yawRate:state.yawRate};const telemetry=state.type===TRANSPORT_TYPES.CAR?stepArcadeCar(state,safeDt,lastInput,arcadeProfile(profile(),physics)):transportStep(state,safeDt,lastInput);if(state.type===TRANSPORT_TYPES.CAR&&worldBlocked(state.x,state.y)){state.x=old.x;state.y=old.y;state.a=old.a;state.v=0;state.vx=0;state.vy=0;state.yawRate=0;}const dx=state.x-old.x,dy=state.y-old.y,dz=state.z-old.z;telemetry.frameDistance=Math.hypot(dx,dy,dz);telemetry.vehicleId=currentId;telemetry.physics={type:physics.type,mass:physics.mass,maxSpeed:physics.maxForwardSpeed,engineForce:physics.engineForce,brakeForce:physics.brakeForce,steeringRate:physics.steeringRate,grip:physics.lateralGrip,turnRadius:physics.turnRadius,calibration:physics.calibration||null,model:state.type===TRANSPORT_TYPES.CAR?'arcade-bicycle':'force-based'};telemetry.calibration=activeCalibration()?{...activeCalibration()}:null;telemetry.actuator={target:{...input},applied:{...lastInput},response:{...actuatorResponse}};state.telemetry=telemetry;state.actuatorState={...actuator};return telemetry;}
 function snapshot(){const v=profile(),t=getTransportTypeProfile(v.type);return{vehicleId:v.id,profile:v,typeProfile:t,state:{...state},physics:{...physics},calibration:activeCalibration()?{...activeCalibration()}:null,calibrationProfile:calibrationProfile?{...calibrationProfile,vehicles:{...(calibrationProfile.vehicles||{})}}:null,input:{...lastInput},actuator:{...actuator},actuatorResponse:{...actuatorResponse},telemetry:transportTelemetry(state,lastInput,physics)};}
 return{get vehicleId(){return currentId;},get profile(){return profile();},get typeProfile(){return getTransportTypeProfile(state.type);},get state(){return state;},get physics(){return physics;},get calibration(){return activeCalibration();},setVehicle,setCalibration,setCalibrationProfile,getCalibration,clearCalibration,clearAllCalibration,setActuatorResponse,resetActuators,control,step,snapshot};
}
