import { VEHICLE_ASSETS } from "../assets/vehicle_icons.js";
import { AUTHORED_TERRAIN, migrateWorld2Point, ARCHIPELAGO_WIDTH, ARCHIPELAGO_HEIGHT, authoredDistricts, AUTHORED_ISLETS, worldPoint, districtPoint, sourceDistrict, remapLegacyScene, remapBridges, isletWalkways, normalizeStreetGeometry } from "../world/archipelago.js";
import { drawArchitecture, drawStreetTree, drawStreetFurniture } from "../render/canvas/architecture.js";
import { velocityForHeading, stepLandVehicle, projectIso, routeInput } from "../simulation/vehicle_dynamics.js";
import { createDriveLab } from "../tools/driving_lab.js";
import { resolveContact, resolveScenery, contact, chassis, captureMotion, solveVehicleMotion, createSpatialIndex, createSceneryIndex } from "../simulation/solid_contacts.js";
import { createWalkSurface } from "../world/walk_surface.js";
import { planEmergencyPassingManeuver, emergencyPassingPathClear } from "../simulation/emergency_passing.js";
import { coastPath, coastPoints, pointInCoast, pointInBeach, BEACH_WIDTH } from "../world/coastline.js";
import { createFreeRoam, drawTransport, VEHICLES, PLANE_RUNWAYS as LEGACY_RUNWAYS } from "../simulation/free_roam.js";
import { visibleOceanChunks } from "../world/ocean_chunks.js";
import { classifySurface, surfaceMovement, createWeather, weatherMovement, WEATHER_PRESETS } from "../simulation/surfaces.js";
import { createCityIncidentDirector, updateCrowdReactions } from "../simulation/incidents.js";
import { advanceTrafficCar, resolveTrafficPair } from "../simulation/traffic_turns.js";
import { streetSurfaceGeometry, createRoadCircuits, createRoadGraph, roadPath, roadTerminals, onRoadSurface, createWalkingRoutes, assignWalkingRoutes, nextWalkingGoal, planStopRoute, advanceRouteActor, drawRoadTerminals } from "../world/street_network.js";
import { createLowtownThreeRenderer } from "../render/three/renderer.js";
import { organicStreetNetwork, fitBuildingsToStreets } from "../world/organic_streets.js";
import { onStreetCollection, corridorRoad, corridorContains, nearestStreet, streetWidth, streetPoints, rectangleClearOfStreets } from "../world/street_corridors.js";
import { createGameMenu } from "../ui/menu.js";
export const RUNTIME_DEPENDENCIES={ARCHIPELAGO_HEIGHT,ARCHIPELAGO_WIDTH,AUTHORED_ISLETS,AUTHORED_TERRAIN,BEACH_WIDTH,LEGACY_RUNWAYS,VEHICLES,VEHICLE_ASSETS,WEATHER_PRESETS,advanceRouteActor,advanceTrafficCar,assignWalkingRoutes,authoredDistricts,captureMotion,chassis,classifySurface,coastPath,coastPoints,contact,corridorContains,corridorRoad,createCityIncidentDirector,createDriveLab,createFreeRoam,createGameMenu,createLowtownThreeRenderer,createRoadCircuits,createRoadGraph,createSceneryIndex,createSpatialIndex,createWalkSurface,createWalkingRoutes,createWeather,districtPoint,drawArchitecture,drawRoadTerminals,drawStreetFurniture,drawStreetTree,drawTransport,emergencyPassingPathClear,fitBuildingsToStreets,isletWalkways,migrateWorld2Point,nearestStreet,nextWalkingGoal,normalizeStreetGeometry,onRoadSurface,onStreetCollection,organicStreetNetwork,planEmergencyPassingManeuver,planStopRoute,pointInBeach,pointInCoast,projectIso,rectangleClearOfStreets,remapBridges,remapLegacyScene,resolveContact,resolveScenery,resolveTrafficPair,roadPath,roadTerminals,routeInput,solveVehicleMotion,sourceDistrict,stepLandVehicle,streetPoints,streetSurfaceGeometry,streetWidth,surfaceMovement,updateCrowdReactions,velocityForHeading,visibleOceanChunks,weatherMovement,worldPoint};
