import './style.css';
import { WORLD } from './game/world.js';
import { ISLANDS, BRIDGES, isLand, islandAt, biomeAt } from './game/islands.js';
import { createTrafficSystem } from './game/traffic.js';
import { createMissionSystem } from './game/missions.js';
import { createPeopleSystem } from './game/people.js';
import { createEventSystem } from './game/events.js';
import { createAIDriver } from './game/ai_driver.js';
import { createTransportSystem } from './game/transport.js';
import { createTransportController } from './game/transport_controller.js';
import { createCityVisuals } from './game/city_visuals.js';
import { buildRoadNetwork, roadSegments, snapToRoad, ROAD_GRID, ROAD_LIMIT, ROAD_WIDTH } from './game/road_authority.js';

const app=document.querySelector('#app');
app.innerHTML=`<main class="shell"><header class="hud"><div class="brand"><span>LOW</span>TOWN <b>// NIGHT SHIFT</b></div><div class="status"><i></i> FREE ROAM <strong id="speed">000</strong> KM/H</div></header><section class="game-wrap"><canvas id="game"></canvas><div class="mission"><small id="job-id">JOB 01</small><strong id="job-title">SHAKE THE NIGHT</strong><span id="job-text">Drive to the amber marker.</span></div><div class="hint">WASD / ARROWS · SPACE HANDBRAKE · I AI DRIVE · R RESET · N NEXT JOB</div><div class="toast" id="toast">ENGINE READY</div></section></main>`;
const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d'),speedEl=document.querySelector('#speed'),toast=document.querySelector('#toast'),jobId=document.querySelector('#job-id'),jobTitle=document.querySelector('#job-title'),jobText=document.querySelector('#job-text'),keys=new Set();
addEventListener('keydown',e=>{const k=e.key.toLowerCase();keys.add(k);if(['arrowup','arrowdown','arrowleft','arrowright',' ','n','r','i'].includes(k))e.preventDefault();});
addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
const buildings=WORLD.buildings,lamps=WORLD.lamps,cityVisuals=createCityVisuals(),CITY_LIMIT=ROAD_LIMIT,testMode=new URLSearchParams(location.search).has('autotest');
const blocked=(x,y)=>{const r=18;if(!isLand(x,y))return true;return buildings.some(([bx,by,bw,bh])=>x>bx-r&&x<bx+bw+r&&y>by-r&&y<by+bh+r);};
const roadNodes=buildRoadNetwork({isLand,blocked,limit:CITY_LIMIT,grid:ROAD_GRID}),roadLines=roadSegments(roadNodes);
function nearestRoadPoint(x,y){let best=null;for(const [a,b] of roadLines){const dx=b.x-a.x,dy=b.y-a.y,len2=dx*dx+dy*dy||1,t=Math.max(0,Math.min(1,((x-a.x)*dx+(y-a.y)*dy)/len2)),px=a.x+dx*t,py=a.y+dy*t,d=Math.hypot(x-px,y-py);if(!best||d<best.distance)best={x:px,y:py,distance:d,heading:Math.atan2(dy,dx)};}return best;}
const start=snapToRoad({x:-320,y:0},roadNodes)||{x:-320,y:0,heading:0};
const playerTransport=createTransportController('sedan',{x:start.x,y:start.y,a:start.heading});
const S={car:playerTransport.state,cam:{x:start.x,y:start.y},target:WORLD.mission,t:0,done:false,damage:0,collisions:0,trafficHits:0,stuck:0,maxSpeed:0,distance:0,missionReward:0,aiActive:testMode,test:{active:testMode}};
function resize(){const r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);canvas.width=Math.max(1,Math.round(r.width*d));canvas.height=Math.max(1,Math.round(r.height*d));ctx.setTransform(d,0,0,d,0,0);}addEventListener('resize',resize);resize();
function iso(x,y){return{x:canvas.clientWidth/2+(x-S.cam.x)*.78+(y-S.cam.y)*.42,y:canvas.clientHeight/2+(y-S.cam.y)*.42-(x-S.cam.x)*.78};}
function poly(points,fill,stroke){ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.closePath();ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.stroke();}}
function ellipseWorld(island){const pts=[];for(let i=0;i<48;i++){const a=i/48*Math.PI*2;pts.push(iso(island.center.x+Math.cos(a)*island.rx,island.center.y+Math.sin(a)*island.ry));}return pts;}
function terrain(){ctx.fillStyle='#0b171b';ctx.fillRect(0,0,canvas.clientWidth,canvas.clientHeight);for(const island of ISLANDS){poly(ellipseWorld(island),island.colors.land,'#0b0d0f');const inner={...island,rx:island.rx-42,ry:island.ry-42};poly(ellipseWorld(inner),island.biome==='FOREST_HIGHLAND'?'#263329':island.biome==='INDUSTRIAL_COAST'?'#292c2d':'#24272a');}for(const b of BRIDGES){const a=iso(b.a.x,b.a.y),z=iso(b.b.x,b.b.y);ctx.strokeStyle='#4b4035';ctx.lineWidth=b.width||40;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(z.x,z.y);ctx.stroke();ctx.strokeStyle='#d6a15a';ctx.lineWidth=2;ctx.setLineDash([10,10]);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(z.x,z.y);ctx.stroke();ctx.setLineDash([]);}}
function roads(){terrain();ctx.lineCap='round';for(const [a,b] of roadLines){const pa=iso(a.x,a.y),pb=iso(b.x,b.y);ctx.strokeStyle='#292c30';ctx.lineWidth=ROAD_WIDTH;ctx.beginPath();ctx.moveTo(pa.x,pa.y);ctx.lineTo(pb.x,pb.y);ctx.stroke();ctx.strokeStyle='rgba(224,154,62,.38)';ctx.lineWidth=2;ctx.setLineDash([18,20]);ctx.beginPath();ctx.moveTo(pa.x,pa.y);ctx.lineTo(pb.x,pb.y);ctx.stroke();}ctx.setLineDash([]);ctx.lineCap='butt';}
function building(x,y,w,h){const island=islandAt(x+w/2,y+h/2);if(!island)return;const top=[iso(x,y),iso(x+w,y),iso(x+w,y+h),iso(x,y+h)],f=top.map(p=>({x:p.x,y:p.y-(island.biome==='FOREST_HIGHLAND'?48:70)}));poly(f,island.biome==='INDUSTRIAL_COAST'?'#3a3b3b':'#34373c','#111317');poly([f[0],f[1],top[1],top[0]],'#292b2e');poly([f[1],f[2],top[2],top[1]],'#202226');for(let yy=18;yy<h;yy+=38)for(let xx=22;xx<w;xx+=48){if(((xx+yy)/38|0)%3===0)continue;const p=iso(x+xx,y+yy);ctx.fillStyle='rgba(224,154,62,.32)';ctx.fillRect(p.x-3,p.y-2,6,4);}}
function lamp(x,y){if(!isLand(x,y))return;const p=iso(x,y);ctx.strokeStyle='#55585d';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(p.x,p.y-35);ctx.stroke();ctx.fillStyle='#e09a3e';ctx.beginPath();ctx.arc(p.x,p.y-39,4,0,Math.PI*2);ctx.fill();}
function target(){const p=iso(S.target.x,S.target.y),r=18+Math.sin(S.t*5)*4;ctx.strokeStyle='#e09a3e';ctx.lineWidth=3;ctx.beginPath();ctx.arc(p.x,p.y,r,0,Math.PI*2);ctx.stroke();ctx.fillStyle='rgba(224,154,62,.18)';ctx.fill();ctx.fillStyle='#e09a3e';ctx.font='bold 10px monospace';ctx.textAlign='center';ctx.fillText('DROP',p.x,p.y-27);}
function playerCar(){const p=iso(S.car.x,S.car.y),f=iso(S.car.x+Math.cos(S.car.a)*10,S.car.y+Math.sin(S.car.a)*10),ang=Math.atan2(f.y-p.y,f.x-p.x),L=46,W=24;ctx.save();ctx.translate(p.x,p.y);ctx.rotate(ang);ctx.fillStyle='rgba(0,0,0,.55)';ctx.beginPath();ctx.ellipse(0,9,34,7,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#252a2e';ctx.beginPath();ctx.moveTo(-28,-10);ctx.lineTo(25,-10);ctx.lineTo(35,6);ctx.lineTo(25,11);ctx.lineTo(-28,11);ctx.lineTo(-36,4);ctx.closePath();ctx.fill();ctx.fillStyle='#e8b84a';ctx.strokeStyle='#171a1e';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(-26,-8);ctx.lineTo(23,-8);ctx.lineTo(31,5);ctx.lineTo(22,8);ctx.lineTo(-25,8);ctx.lineTo(-31,3);ctx.closePath();ctx.fill();ctx.stroke();ctx.fillStyle='#1b2228';ctx.beginPath();ctx.moveTo(-13,-5);ctx.lineTo(10,-5);ctx.lineTo(20,4);ctx.lineTo(-18,4);ctx.closePath();ctx.fill();ctx.fillStyle='#d4523a';ctx.fillRect(-27,3,7,3);ctx.fillStyle='#fff1a7';ctx.fillRect(22,2,6,4);ctx.fillStyle='#0a0b0d';ctx.fillRect(-20,-12,11,4);ctx.fillRect(11,-12,11,4);ctx.restore();}
function speed(){return Math.hypot(S.car.vx,S.car.vy);}
function keepPlayerOnRoad(before){const near=nearestRoadPoint(S.car.x,S.car.y);if(!near||near.distance>ROAD_WIDTH*.48){S.car.x=before.x;S.car.y=before.y;S.car.a=before.a;S.car.v=0;S.car.vx=0;S.car.vy=0;S.car.yawRate=0;S.stuck++;return false;}S.stuck=0;return true;}
function drive(input,dt){const before={x:S.car.x,y:S.car.y,a:S.car.a};playerTransport.step(dt,input);keepPlayerOnRoad(before);S.distance+=speed()*dt;}
function trafficCollisions(){const now=performance.now();for(const n of traffic.cars){const dx=n.x-S.car.x,dy=n.y-S.car.y,d=Math.hypot(dx,dy);if(d<34&&now-(n.hitAt||0)>550){const nx=dx/(d||1),ny=dy/(d||1),impact=clamp(Math.max(20,speed()-n.v),20,35);S.car.vx-=nx*impact*.06;S.car.vy-=ny*impact*.06;n.v=Math.max(0,n.v-impact*.05);const push=Math.min(12,(34-d)*.72+1);S.car.x-=nx*push*.35;S.car.y-=ny*push*.35;n.x+=nx*push*.65;n.y+=ny*push*.65;n.hitAt=now;S.trafficHits++;S.damage+=Math.min(2,impact/120);toast.textContent='TRAFFIC HIT';}}}
const traffic=createTrafficSystem({nodes:roadNodes,blocked}),people=createPeopleSystem({nodes:roadNodes,blocked}),events=createEventSystem({nodes:roadNodes}),missions=createMissionSystem(WORLD),ai=createAIDriver({nodes:roadNodes,blocked,getTraffic:()=>traffic.cars}),transport=createTransportSystem();
function refreshMission(){const m=missions.state(),idx=missions.templates.findIndex(t=>t.id===m.id);S.target=m.target;jobId.textContent=`JOB 0${idx+1}`;jobTitle.textContent=m.title;jobText.textContent=`${m.text}  $${m.reward}`;}
function reset(){const near=nearestRoadPoint(S.car.x,S.car.y)||start;S.car.x=near.x;S.car.y=near.y;S.car.z=0;S.car.a=near.heading;S.car.v=0;S.car.vx=0;S.car.vy=0;S.car.vz=0;S.car.yawRate=0;S.car.distance=0;S.car.age=0;playerTransport.resetActuators();playerTransport.setVehicle('sedan');S.cam.x=S.car.x;S.cam.y=S.car.y;S.done=false;S.damage=0;S.collisions=0;S.trafficHits=0;S.stuck=0;S.maxSpeed=0;S.distance=0;if(S.aiActive)ai.start(S.car);else ai.state.enabled=false;toast.textContent=S.aiActive?'AI DRIVER READY':'ENGINE READY';toast.classList.remove('hot');refreshMission();}
function toggleAI(){S.aiActive=!S.aiActive;S.test.active=S.aiActive;if(S.aiActive){ai.start(S.car);toast.textContent='AI DRIVE // ONLINE';}else{ai.state.enabled=false;toast.textContent='AI DRIVE // OFF';}}
refreshMission();if(testMode)reset();window.__LOWTOWN_ACTIONS__={toggleAI,reset};
function update(dt){if(keys.has('n')){missions.next();S.done=false;keys.delete('n');refreshMission();toast.textContent='NEW JOB';}if(keys.has('r')){reset();keys.delete('r');}if(keys.has('i')){toggleAI();keys.delete('i');}if(S.aiActive){const control=ai.update(S.car,dt);if(control)drive(control,dt);S.distance=ai.state.distance;}else{const mobile=window.__LOWTOWN_MOBILE_DRIVE__?.read?.();const hasMobile=mobile&&(['throttle','steer','brake','handbrake'].some(k=>k==='handbrake'?mobile.handbrake:Math.abs(Number(mobile[k])||0)>.01));if(hasMobile)drive(mobile,dt);else{const u=keys.has('w')||keys.has('arrowup'),d=keys.has('s')||keys.has('arrowdown'),l=keys.has('a')||keys.has('arrowleft'),r=keys.has('d')||keys.has('arrowright');drive({throttle:u?1:d?-1:0,brake:d?1:0,steer:(r?1:0)-(l?1:0),handbrake:keys.has(' ')},dt);}}events.update(dt,S.car);traffic.update(dt,S.car,events.state());people.update(dt,S.car,0);transport.update(dt);trafficCollisions();if(!S.done&&missions.update(S.car)){S.done=true;S.missionReward+=missions.state().reward;S.car.v*=.45;S.car.vx*=.45;S.car.vy*=.45;toast.textContent=`JOB COMPLETE // +$${missions.state().reward}`;toast.classList.add('hot');}const v=speed();S.maxSpeed=Math.max(S.maxSpeed,v);S.cam.x+=(S.car.x-S.cam.x)*Math.min(1,dt*4.5);S.cam.y+=(S.car.y-S.cam.y)*Math.min(1,dt*4.5);speedEl.textContent=String(Math.round(v*.19)).padStart(3,'0');}
function draw(){roads();for(const b of buildings)building(...b);for(const l of lamps)lamp(...l);cityVisuals.draw(ctx,iso,buildings,lamps,S.t);traffic.draw(ctx,iso);people.draw(ctx,iso,S.car);transport.draw(ctx,iso,S.t*1000);target();playerCar();}
let last=performance.now();function frame(now){const dt=Math.min(.05,(now-last)/1000);last=now;S.t+=dt;update(dt);draw();requestAnimationFrame(frame);}requestAnimationFrame(frame);
window.__LOWTOWN_AI=ai;window.__LOWTOWN_TRANSPORT={player:playerTransport,system:transport.state};window.__LOWTOWN_TEST={state:()=>({x:S.car.x,y:S.car.y,speed:speed(),maxSpeed:S.maxSpeed,distance:S.distance,collisions:S.collisions,trafficHits:S.trafficHits,damage:S.damage,stuck:S.stuck,recoveries:ai.state.recoveries,replans:ai.state.replans,safeStarts:ai.state.safeStarts,trafficCars:traffic.cars.length,pedestrians:people.people.length,missionComplete:S.done,missionReward:S.missionReward,mode:ai.state.mode,ttc:ai.state.prediction.ttc,risk:ai.state.prediction.risk,aiActive:S.aiActive,roadDistance:nearestRoadPoint(S.car.x,S.car.y)?.distance??Infinity})};
