import './style.css';
import './game/mobile_controls_v2.js';
import { WORLD } from './game/world.js';
import { ISLANDS, BRIDGES, isLand, islandAt } from './game/islands.js';
import { createTrafficSystem } from './game/traffic.js';
import { createMissionSystem } from './game/missions.js';
import { createPeopleSystem } from './game/people.js';
import { createEventSystem } from './game/events.js';
import { createAIDriver } from './game/ai_driver.js';
import { createTransportSystem } from './game/transport.js';
import { createTransportController } from './game/transport_controller.js';
import { loadSave, saveState } from './game/save_state.js';
import { buildRoadNetwork, roadSegments, snapToRoad, ROAD_GRID, ROAD_LIMIT, ROAD_WIDTH } from './game/road_authority.js';

const app=document.querySelector('#app');
app.innerHTML=`<main class="shell"><header class="hud"><div class="brand"><span>LOW</span>TOWN <b>// NIGHT SHIFT</b></div><div class="status"><i></i> FREE ROAM <strong id="speed">000</strong> KM/H <em id="money">$000</em></div></header><section class="game-wrap"><canvas id="game"></canvas><div class="mission"><small id="job-id">JOB 01</small><strong id="job-title">SHAKE THE NIGHT</strong><span id="job-text">Drive to the amber marker.</span><div class="progress" id="job-progress">DIST 000m · OBJECTIVE 0/1</div></div><div class="hint">ARROWS / WASD · SPACE HANDBRAKE · I AI DRIVE · R RESET · N NEXT JOB</div><div class="toast" id="toast"></div><div class="debug-overlay" id="debug-overlay"></div></section></main>`;
const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d'),speedEl=document.querySelector('#speed'),moneyEl=document.querySelector('#money'),toast=document.querySelector('#toast'),jobId=document.querySelector('#job-id'),jobTitle=document.querySelector('#job-title'),jobText=document.querySelector('#job-text'),jobProgress=document.querySelector('#job-progress'),debugOverlay=document.querySelector('#debug-overlay'),keys=new Set();
const params=new URLSearchParams(location.search),debugMode=params.has('debug')||params.has('aiTest');
let toastTimer=0;
function showToast(message,{hot=false,duration=2}={}){toast.textContent=message;toast.classList.toggle('hot',hot);toast.classList.add('visible');toastTimer=duration;}
function dismissToast(){toast.classList.remove('visible','hot');toastTimer=0;}
addEventListener('keydown',e=>{const k=e.key.toLowerCase();keys.add(k);if(['arrowup','arrowdown','arrowleft','arrowright',' ','n','r','i'].includes(k))e.preventDefault();if(k==='n'||k==='r'||k==='i'||k.startsWith('arrow'))dismissToast();});
addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
const buildings=WORLD.buildings,lamps=WORLD.lamps,CITY_LIMIT=ROAD_LIMIT,testMode=params.has('autotest');
const blocked=(x,y)=>{const r=18;if(!isLand(x,y))return true;return buildings.some(([bx,by,bw,bh])=>x>bx-r&&x<bx+bw+r&&y>by-r&&y<by+bh+r);};
const roadNodes=buildRoadNetwork({isLand,blocked,limit:CITY_LIMIT,grid:ROAD_GRID}),roadLines=roadSegments(roadNodes);
function nearestRoadPoint(x,y){let best=null;for(const [a,b] of roadLines){const dx=b.x-a.x,dy=b.y-a.y,len2=dx*dx+dy*dy||1,t=Math.max(0,Math.min(1,((x-a.x)*dx+(y-a.y)*dy)/len2)),px=a.x+dx*t,py=a.y+dy*t,d=Math.hypot(x-px,y-py);if(!best||d<best.distance)best={x:px,y:py,distance:d,heading:Math.atan2(dy,dx)};}return best;}
const start=snapToRoad({x:-320,y:0},roadNodes)||{x:-320,y:0,heading:0};
const playerTransport=createTransportController('sedan',{x:start.x,y:start.y,a:start.heading,roadLines,vehicleLength:56,vehicleWidth:28});
const save=loadSave();
const S={car:playerTransport.state,cam:{x:start.x,y:start.y},target:WORLD.mission,t:0,done:false,damage:0,collisions:0,trafficHits:0,stuck:0,maxSpeed:0,distance:0,missionReward:0,money:save?.money||0,completedJobs:save?.completedJobs||0,aiActive:testMode,test:{active:testMode},aiDebug:{frames:0,elapsed:0,last:null,movedDistance:0,initialX:start.x,initialY:start.y},objectiveTrace:[]};
function resize(){const r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);canvas.width=Math.max(1,Math.round(r.width*d));canvas.height=Math.max(1,Math.round(r.height*d));ctx.setTransform(d,0,0,d,0,0);}addEventListener('resize',resize);resize();
const VIEW_ZOOM=.78;
function iso(x,y){return{x:canvas.clientWidth/2+(x-S.cam.x)*VIEW_ZOOM,y:canvas.clientHeight/2+(y-S.cam.y)*VIEW_ZOOM};}
function rectWorld(x,y,w,h){const p=iso(x,y);return{x:p.x,y:p.y,w:w*VIEW_ZOOM,h:h*VIEW_ZOOM};}
function terrain(){ctx.fillStyle='#0b1114';ctx.fillRect(0,0,canvas.clientWidth,canvas.clientHeight);for(const island of ISLANDS){const p=iso(island.center.x,island.center.y);ctx.fillStyle=island.colors.land;ctx.beginPath();ctx.ellipse(p.x,p.y,island.rx*VIEW_ZOOM,island.ry*VIEW_ZOOM,0,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#0b0d0f';ctx.lineWidth=3;ctx.stroke();ctx.fillStyle=island.biome==='FOREST_HIGHLAND'?'#263329':island.biome==='INDUSTRIAL_COAST'?'#292c2d':'#24272a';ctx.beginPath();ctx.ellipse(p.x,p.y,Math.max(1,island.rx-42)*VIEW_ZOOM,Math.max(1,island.ry-42)*VIEW_ZOOM,0,0,Math.PI*2);ctx.fill();}for(const b of BRIDGES){const a=iso(b.a.x,b.a.y),z=iso(b.b.x,b.b.y);ctx.strokeStyle='#4b4035';ctx.lineWidth=(b.width||40)*VIEW_ZOOM;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(z.x,z.y);ctx.stroke();ctx.strokeStyle='#d6a15a';ctx.lineWidth=2;ctx.setLineDash([10,10]);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(z.x,z.y);ctx.stroke();ctx.setLineDash([]);}}
function roads(){terrain();ctx.save();ctx.beginPath();for(const island of ISLANDS){const p=iso(island.center.x,island.center.y);ctx.ellipse(p.x,p.y,island.rx*VIEW_ZOOM,island.ry*VIEW_ZOOM,0,0,Math.PI*2);}ctx.clip();ctx.lineCap='round';ctx.lineJoin='round';for(const [a,b] of roadLines){const pa=iso(a.x,a.y),pb=iso(b.x,b.y);ctx.strokeStyle='#16191d';ctx.lineWidth=(ROAD_WIDTH+10)*VIEW_ZOOM;ctx.beginPath();ctx.moveTo(pa.x,pa.y);ctx.lineTo(pb.x,pb.y);ctx.stroke();ctx.strokeStyle='#292c30';ctx.lineWidth=ROAD_WIDTH*VIEW_ZOOM;ctx.beginPath();ctx.moveTo(pa.x,pa.y);ctx.lineTo(pb.x,pb.y);ctx.stroke();ctx.strokeStyle='rgba(224,154,62,.30)';ctx.lineWidth=2;ctx.setLineDash([16,18]);ctx.beginPath();ctx.moveTo(pa.x,pa.y);ctx.lineTo(pb.x,pb.y);ctx.stroke();ctx.setLineDash([]);}ctx.restore();}
function building(x,y,w,h){const r=rectWorld(x,y,w,h);ctx.fillStyle='rgba(0,0,0,.42)';ctx.fillRect(r.x+5,r.y+7,r.w,r.h);ctx.fillStyle=islandAt(x+w/2,y+h/2)?.biome==='INDUSTRIAL_COAST'?'#343638':'#303338';ctx.fillRect(r.x,r.y,r.w,r.h);ctx.strokeStyle='#111317';ctx.lineWidth=2;ctx.strokeRect(r.x,r.y,r.w,r.h);const cols=Math.max(1,Math.floor(w/55)),rows=Math.max(1,Math.floor(h/42));for(let yy=0;yy<rows;yy++)for(let xx=0;xx<cols;xx++){if((xx*7+yy*3+Math.floor(x))%4===0)continue;const wx=x+(xx+.5)*w/cols,wy=y+(yy+.5)*h/rows,p=iso(wx,wy);ctx.fillStyle='rgba(224,154,62,.34)';ctx.fillRect(p.x-3,p.y-2,6,4);}}
function lamp(x,y){if(!isLand(x,y))return;const p=iso(x,y),g=ctx.createRadialGradient(p.x,p.y,1,p.x,p.y,22);g.addColorStop(0,'rgba(255,211,130,.22)');g.addColorStop(1,'rgba(224,154,62,0)');ctx.fillStyle=g;ctx.beginPath();ctx.arc(p.x,p.y,22,0,Math.PI*2);ctx.fill();ctx.fillStyle='#e09a3e';ctx.beginPath();ctx.arc(p.x,p.y,3,0,Math.PI*2);ctx.fill();}
function target(){const p=iso(S.target.x,S.target.y),r=(18+Math.sin(S.t*5)*4)*VIEW_ZOOM;ctx.strokeStyle='#e09a3e';ctx.lineWidth=3;ctx.beginPath();ctx.arc(p.x,p.y,r,0,Math.PI*2);ctx.stroke();ctx.fillStyle='rgba(224,154,62,.18)';ctx.fill();ctx.fillStyle='#e09a3e';ctx.font='bold 10px monospace';ctx.textAlign='center';ctx.fillText('DROP',p.x,p.y-r-9);}
function playerCar(){const p=iso(S.car.x,S.car.y),ang=S.car.a;ctx.save();ctx.translate(p.x,p.y);ctx.rotate(ang);ctx.fillStyle='rgba(0,0,0,.52)';ctx.beginPath();ctx.ellipse(-1,5,30*VIEW_ZOOM,13*VIEW_ZOOM,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#252a2e';ctx.fillRect(-28*VIEW_ZOOM,-12*VIEW_ZOOM,56*VIEW_ZOOM,24*VIEW_ZOOM);ctx.fillStyle='#e8b84a';ctx.strokeStyle='#171a1e';ctx.lineWidth=2;ctx.fillRect(-24*VIEW_ZOOM,-9*VIEW_ZOOM,48*VIEW_ZOOM,18*VIEW_ZOOM);ctx.strokeRect(-24*VIEW_ZOOM,-9*VIEW_ZOOM,48*VIEW_ZOOM,18*VIEW_ZOOM);ctx.fillStyle='#1b2228';ctx.fillRect(-12*VIEW_ZOOM,-7*VIEW_ZOOM,24*VIEW_ZOOM,9*VIEW_ZOOM);ctx.fillStyle='#d4523a';ctx.fillRect(-24*VIEW_ZOOM,4*VIEW_ZOOM,7*VIEW_ZOOM,3*VIEW_ZOOM);ctx.fillStyle='#fff1a7';ctx.fillRect(17*VIEW_ZOOM,4*VIEW_ZOOM,7*VIEW_ZOOM,3*VIEW_ZOOM);ctx.restore();}
function speed(){return Math.hypot(S.car.vx,S.car.vy);}
function keepPlayerOnRoad(before){const near=nearestRoadPoint(S.car.x,S.car.y);if(!near||near.distance>ROAD_WIDTH*.62){S.car.x=before.x;S.car.y=before.y;S.car.a=before.a;S.car.v*=.25;S.car.vx*=.25;S.car.vy*=.25;S.car.yawRate=0;S.stuck++;return false;}S.stuck=0;return true;}
function drive(input,dt){const before={x:S.car.x,y:S.car.y,a:S.car.a};playerTransport.step(dt,input);keepPlayerOnRoad(before);S.distance+=speed()*dt;}
const traffic=createTrafficSystem({nodes:roadNodes,blocked}),people=createPeopleSystem({nodes:roadNodes,blocked}),events=createEventSystem({nodes:roadNodes}),missions=createMissionSystem(WORLD),ai=createAIDriver({nodes:roadNodes,blocked,getTraffic:()=>traffic.cars}),transport=createTransportSystem();
if(S.completedJobs>0)missions.restore?.(S.completedJobs);
function refreshMission(){const m=missions.state(),idx=missions.templates.findIndex(t=>t.id===m.id);S.target=m.target;jobId.textContent=`JOB 0${idx+1}`;jobTitle.textContent=m.title;jobText.textContent=`${m.text}  $${m.reward}`;moneyEl.textContent=`$${String(Math.floor(S.money)).padStart(3,'0')}`;const d=Math.round(Math.hypot(S.car.x-S.target.x,S.car.y-S.target.y));const objective=m.complete?1:0;jobProgress.innerHTML=`DIST <b>${String(d).padStart(3,'0')}m</b> · OBJECTIVE <b>${objective}/1</b>`;}
function persist(){saveState({completedJobs:S.completedJobs,money:S.money});}
function reset(){const near=nearestRoadPoint(S.car.x,S.car.y)||start;S.car.x=near.x;S.car.y=near.y;S.car.z=0;S.car.a=near.heading;S.car.v=0;S.car.vx=0;S.car.vy=0;S.car.vz=0;S.car.yawRate=0;S.car.distance=0;S.car.age=0;playerTransport.resetActuators();playerTransport.setVehicle('sedan');S.cam.x=S.car.x;S.cam.y=S.car.y;S.done=false;S.damage=0;S.collisions=0;S.trafficHits=0;S.stuck=0;S.maxSpeed=0;S.distance=0;S.objectiveTrace=[];S.aiDebug={frames:0,elapsed:0,last:null,movedDistance:0,initialX:S.car.x,initialY:S.car.y};if(S.aiActive)ai.start(S.car);else ai.state.enabled=false;toast.classList.remove('visible','hot');toastTimer=0;refreshMission();}
function toggleAI(){S.aiActive=!S.aiActive;S.test.active=S.aiActive;if(S.aiActive){ai.start(S.car);showToast('AI DRIVE // ONLINE',{duration:1.5});}else{ai.state.enabled=false;showToast('AI DRIVE // OFF',{duration:1.5});}}
refreshMission();if(testMode)reset();window.__LOWTOWN_ACTIONS__={toggleAI,reset};
function updateAI(dt){const before={x:S.car.x,y:S.car.y,vx:S.car.vx||0,vy:S.car.vy||0};const control=ai.update(S.car,dt);if(control)drive(control,dt);const applied={vx:S.car.vx||0,vy:S.car.vy||0,v:speed(),x:S.car.x,y:S.car.y};const moved=Math.hypot(applied.x-before.x,applied.y-before.y);S.aiDebug.frames++;S.aiDebug.elapsed+=dt;S.aiDebug.movedDistance+=moved;S.aiDebug.last={frame:S.aiDebug.frames,command:{...control},applied,delta:{x:applied.x-before.x,y:applied.y-before.y},prediction:{ttc:ai.state.prediction.ttc,risk:ai.state.prediction.risk,safe:ai.state.prediction.safe}};if(debugMode){const raw=`AI f${S.aiDebug.frames} cmd=${JSON.stringify(control)} applied(v=${applied.v.toFixed(2)},vx=${applied.vx.toFixed(2)},vy=${applied.vy.toFixed(2)}) pos=(${applied.x.toFixed(1)},${applied.y.toFixed(1)})`;console.debug(raw);debugOverlay.classList.add('active');debugOverlay.textContent=`AI INTEGRATION\n${raw}\nroute=${ai.state.route.length} node=${ai.state.node} mode=${ai.state.mode}\npred safe=${ai.state.prediction.safe} ttc=${Number.isFinite(ai.state.prediction.ttc)?ai.state.prediction.ttc.toFixed(2):'INF'} risk=${ai.state.prediction.risk.toFixed(2)}\nplayer entities/frame=1 · traffic=${traffic.cars.length}`;}return control;}
function update(dt){if(keys.has('n')){if(missions.next()){S.done=false;refreshMission();showToast('NEW JOB',{duration:1.2});}else showToast('CHAIN COMPLETE',{duration:1.5});keys.delete('n');}if(keys.has('r')){reset();keys.delete('r');}if(keys.has('i')){toggleAI();keys.delete('i');}if(S.aiActive)updateAI(dt);else{const u=keys.has('w')||keys.has('arrowup'),d=keys.has('s')||keys.has('arrowdown'),l=keys.has('a')||keys.has('arrowleft'),r=keys.has('d')||keys.has('arrowright');drive({throttle:u?1:d?-1:0,brake:d?1:0,steer:(r?1:0)-(l?1:0),handbrake:keys.has(' ')},dt);}events.update(dt,S.car);traffic.update(dt,S.car,events.state());const contacts=traffic.consumeCollisions?.()||[];if(contacts.length){S.collisions+=contacts.length;S.trafficHits+=contacts.filter(c=>c.type==='player-npc').length;showToast('TRAFFIC HIT',{hot:true,duration:2});}people.update(dt,S.car,0,traffic.cars);transport.update(dt);if(!S.done&&missions.update(S.car)){S.done=true;const reward=missions.state().reward;S.missionReward+=reward;S.money+=reward;S.completedJobs=Math.max(S.completedJobs,missions.state().completedJobs);persist();S.car.v*=.45;S.car.vx*=.45;S.car.vy*=.45;showToast(`JOB COMPLETE // +$${reward}`,{hot:true,duration:2});refreshMission();}if(toastTimer>0){toastTimer=Math.max(0,toastTimer-dt);if(toastTimer===0)dismissToast();}const v=speed();S.maxSpeed=Math.max(S.maxSpeed,v);S.cam.x+=(S.car.x-S.cam.x)*Math.min(1,dt*4.5);S.cam.y+=(S.car.y-S.cam.y)*Math.min(1,dt*4.5);speedEl.textContent=String(Math.round(v*.19)).padStart(3,'0');moneyEl.textContent=`$${String(Math.floor(S.money)).padStart(3,'0')}`;const m=missions.state(),d=Math.round(Math.hypot(S.car.x-S.target.x,S.car.y-S.target.y));if(debugMode){const trace={t:S.t,x:S.car.x,y:S.car.y,targetX:S.target.x,targetY:S.target.y,distance:d};S.objectiveTrace.push(trace);console.debug(`DIST_TRACE t=${trace.t.toFixed(2)} player=(${trace.x.toFixed(2)},${trace.y.toFixed(2)}) target=(${trace.targetY.toFixed(2)}) dist=${trace.distance}`);}jobProgress.innerHTML=`DIST <b>${String(d).padStart(3,'0')}m</b> · OBJECTIVE <b>${m.complete?1:0}/1</b>`;}
function draw(){roads();for(const b of buildings)building(...b);for(const l of lamps)lamp(...l);traffic.draw(ctx,iso);people.draw(ctx,iso,S.car);transport.draw(ctx,iso,S.t*1000);target();playerCar();if(debugMode){const entityCount=1+traffic.cars.length+people.people.length;debugOverlay.textContent+=`\nentities/frame=${entityCount} (player=1)`;}}
let last=performance.now();function frame(now){const dt=Math.min(.05,(now-last)/1000);last=now;S.t+=dt;update(dt);draw();requestAnimationFrame(frame);}requestAnimationFrame(frame);
window.__LOWTOWN_AI=ai;window.__LOWTOWN_TRANSPORT={player:playerTransport,system:transport.state};window.__LOWTOWN_TEST={state:()=>({x:S.car.x,y:S.car.y,speed:speed(),maxSpeed:S.maxSpeed,distance:S.distance,collisions:S.collisions,trafficHits:S.trafficHits,damage:S.damage,stuck:S.stuck,recoveries:ai.state.recoveries,replans:ai.state.replans,safeStarts:ai.state.safeStarts,trafficCars:traffic.cars.length,pedestrians:people.people.length,missionComplete:S.done,missionReward:S.missionReward,money:S.money,completedJobs:S.completedJobs,mode:ai.state.mode,ttc:S.aiActive?S.ai.state.prediction.ttc:0,risk:S.aiActive?S.ai.state.prediction.risk:0,aiActive:S.aiActive,roadDistance:nearestRoadPoint(S.car.x,S.car.y)?.distance??Infinity,targetX:S.target.x,targetY:S.target.y,objectiveDistance:Math.hypot(S.car.x-S.target.x,S.car.y-S.target.y),objectiveTrace:S.objectiveTrace.slice(),aiDebug:S.aiDebug})};
